from .change_language import get_languages_keyboard
from .main_menu import get_main_keyboard
from .subscribes_menu import get_subscribes_keyboard
from .move import get_move_keyboard
from .balance import get_balance_keyboard
from .cancel import get_cancel_keyboard
from .booksearch import get_search_keyboard
from .payment import get_payment_keyboard
from .buy_book import get_book_buy_keyboard
from .pay import get_pay_keyboard
from .fundraising import get_fundraising_keyboard
from .fund_book import get_fund_book_keyboard
from .subscribe_yoomoney_pay import get_yoomoney_pay_keyboard
from .small_pay_tg_keyboard import get_small_pay_tg_keyboard
from .close import get_close_keyboard
